name: Build MODGD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Geode mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: given
          target: Win64
          build-config: Release

      - name: Upload .geode
        uses: actions/upload-artifact@v4
        with:
          name: MODGD-Platformer-Save
          path: ${{ steps.build.outputs.build-output }}
